stages:
  - lint

php-cs-fixer:
  image: composer:2.1
  stage: lint
  before_script:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - export COMPOSER_CACHE_DIR=/cache/composer
    - export COMPOSER_NO_INTERACTION=1
    - composer req --ignore-platform-reqs --update-no-dev friendsofphp/php-cs-fixer ^3.0
  script:
    - ./vendor/bin/php-cs-fixer fix --dry-run
