# Select image from https://hub.docker.com/_/php/
image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

# Select what we should cache
cache:
  key: $CI_COMMIT_REF_NAME
  paths:
  - .Build/

stages:
  - build
  - code quality
  - test

install:
  stage: build
  script:
    - composer install

services:
  - mysql

lint:
  stage: code quality
  script:
    - composer run ci:php:lint

php-cs-fixer:
  stage: code quality
  script:
    - composer run ci:php:php-cs-fixer:dry

tests:functional:
  stage: test
  script:
    - composer run ci:tests:functional
    - ls -lah
  artifacts:
    reports:
      junit: functional-test-report.xml
      cobertura: functional-tests-coverage.xml
