services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Localizationteam\Localizer\:
    resource: '../Classes/*'

  Localizationteam\Localizer\Handler\:
    resource: '../Classes/Handler/*'
    public: true

  Localizationteam\Localizer\Controller\SettingsController:
    tags: [ 'backend.controller' ]

  Localizationteam\Localizer\Controller\SelectorController:
    tags: [ 'backend.controller' ]

  Localizationteam\Localizer\Controller\CartController:
    tags: [ 'backend.controller' ]
